/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package javadatabase;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/**
 *
 * @author agrahizbullah
 */
public class TampilanGUI extends javax.swing.JFrame {

    private int selectedId = -1;

    DefaultTableModel modelMahasiswa;

    /**
     * Creates new form MainFrame
     */
    public TampilanGUI() {
        initComponents();
        tampilData();
        hitungDanTampilkanBiaya();
        setLocationRelativeTo(null);
    }

    // Tambahkan method ini di dalam class TampilanGUI.java
    private void hitungDanTampilkanBiaya() {
        try {
            // 1. Ambil input SKS dan Jenis
            // Pastikan SKS tidak kosong sebelum parsing
            if (txtsks.getText().isEmpty()) {
                lblBiaya.setText("SKS kosong!");
                return;
            }

            int sks = Integer.parseInt(txtsks.getText());
            String jenis = cbJenis.getSelectedItem().toString();

            Mahasiswa mhs; // Objek Mahasiswa (Polymorphism)

            // 2. Tentukan class turunan mana yang akan dipakai
            switch (jenis) {
                case "Reguler":
                    // Instansiasi Mahasiswa Reguler
                    mhs = new MahasiswaReguler(sks);
                    break;
                case "Beasiswa":
                    // Instansiasi Mahasiswa Beasiswa
                    mhs = new MahasiswaBeasiswa(sks);
                    break;
                case "Internasional":
                    // Instansiasi Mahasiswa Internasional
                    mhs = new MahasiswaInternasional(sks);
                    break;
                default:
                    mhs = new Mahasiswa(sks, jenis);
                    break;
            }

            // 3. Panggil method hitungBiayaKuliah() (Panggilan Polimorfik)
            // Java akan secara otomatis menjalankan rumus dari class yang benar (Reguler/Beasiswa/Internasional)
            double totalBiaya = mhs.hitungBiayaKuliah();

            // 4. Format dan Tampilkan biaya ke lblBiaya
            java.text.DecimalFormat formatter = new java.text.DecimalFormat("Rp #,###,###.00");
            lblBiaya.setText(formatter.format(totalBiaya));

        } catch (NumberFormatException e) {
            // Jika input SKS bukan angka
            lblBiaya.setText("SKS harus angka!");
        } catch (Exception e) {
            // Catch all untuk error lain
            lblBiaya.setText("Error hitung biaya: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNama = new javax.swing.JLabel();
        lblNIM = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtnim = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMahasiswa = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttahun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCSV = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbJenis = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtsks = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblBiaya = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setText("Masukkan Nama");

        lblNIM.setText("Masukkan NIM");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        tblMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tahun Masuk", "Jenis Mahasiswa", "SKS", "Biaya Kuliahl"
            }
        ));
        tblMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMahasiswa);

        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("Update");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("Tahun Masuk");

        btnCSV.setText("CSV");
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        jLabel3.setText("Jenis Mahasiswa");

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Beasiswa", "Internasional" }));
        cbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisActionPerformed(evt);
            }
        });

        jLabel5.setText("SKS");

        txtsks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsksActionPerformed(evt);
            }
        });

        jLabel6.setText("Biaya Kuliah");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addComponent(lblBiaya))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtsks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbJenis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNama)
                                .addGap(52, 52, 52)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNIM)
                                .addGap(63, 63, 63)
                                .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addGap(12, 12, 12)
                        .addComponent(btnCSV)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNama)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNIM)
                            .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBiaya)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnHapus)
                            .addComponent(btnCSV)
                            .addComponent(btnSubmit))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // semua sel tidak bisa diubah langsung
            }
        };
        model.addColumn("ID");
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Tahun Masuk");
        model.addColumn("Jenis Mahasiswa"); // Kolom baru
        model.addColumn("SKS");
        model.addColumn("Biaya Kuliah");
        // Kolom baru

// load data dari DB
        try (
                Connection conn = KoneksiDB.getConnection(); Statement st = conn.createStatement(); ResultSet rs = st.executeQuery("SELECT id, nim, nama, tahunmasuk, jenis_mahasiswa, sks, biaya_kuliah FROM mahasiswa ORDER BY id")) { // QUERY DIPERBARUI

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nim"),
                    rs.getString("nama"),
                    rs.getInt("tahunmasuk"),
                    rs.getString("jenis_mahasiswa"), // Ambil data jenis_mahasiswa
                    rs.getInt("sks"), // Ambil data sks
                    rs.getInt("biaya_kuliah")
                });
            }

            tblMahasiswa.setModel(model);
            tblMahasiswa.getColumnModel().getColumn(0).setMinWidth(0);
            tblMahasiswa.getColumnModel().getColumn(0).setMaxWidth(0);
            tblMahasiswa.getColumnModel().getColumn(0).setWidth(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {
            String nim = txtnim.getText();
            String nama = txtnama.getText();
            int tahunmasuk = Integer.parseInt(txttahun.getText());
            String jenis = cbJenis.getSelectedItem().toString();
            int sks = Integer.parseInt(txtsks.getText());

            // Hitung biaya berdasarkan jenis mahasiswa
            Mahasiswa mhs;
            switch (jenis) {
                case "Reguler":
                    mhs = new MahasiswaReguler(sks);
                    break;
                case "Beasiswa":
                    mhs = new MahasiswaBeasiswa(sks);
                    break;
                case "Internasional":
                    mhs = new MahasiswaInternasional(sks);
                    break;
                default:
                    mhs = new Mahasiswa(sks, jenis);
            }
            double biaya = mhs.hitungBiayaKuliah();

            // Perbaikan penting: tambahkan biaya_kuliah ke query
            Connection conn = KoneksiDB.getConnection();
            String sql = "INSERT INTO mahasiswa (nim, nama, tahunmasuk, jenis_mahasiswa, sks, biaya_kuliah) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sql);

            ps.setString(1, nim);
            ps.setString(2, nama);
            ps.setInt(3, tahunmasuk);
            ps.setString(4, jenis);
            ps.setInt(5, sks);
            ps.setDouble(6, biaya); // ← WAJIB!! INI YANG BELUM ADA

            ps.executeUpdate();

            tampilData();
            clear();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan, biaya terhitung!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Submit: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu!");
            return;
        }

        try {
            String nim = txtnim.getText();
            String nama = txtnama.getText();
            int tahunmasuk = Integer.parseInt(txttahun.getText());
            String jenis = cbJenis.getSelectedItem().toString();
            int sks = Integer.parseInt(txtsks.getText());

            Mahasiswa mhs;
            switch (jenis) {
                case "Reguler":
                    mhs = new MahasiswaReguler(sks);
                    break;
                case "Beasiswa":
                    mhs = new MahasiswaBeasiswa(sks);
                    break;
                case "Internasional":
                    mhs = new MahasiswaInternasional(sks);
                    break;
                default:
                    mhs = new Mahasiswa(sks, jenis);
            }
            double biaya = mhs.hitungBiayaKuliah();

            String sql = "UPDATE mahasiswa SET nim=?, nama=?, tahunmasuk=?, jenis_mahasiswa=?, sks=?, biaya_kuliah=? WHERE id=?";
            Connection conn = KoneksiDB.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, nim);
            pst.setString(2, nama);
            pst.setInt(3, tahunmasuk);
            pst.setString(4, jenis);
            pst.setInt(5, sks);
            pst.setDouble(6, biaya);
            pst.setInt(7, selectedId);

            pst.executeUpdate();

            tampilData();
            clear();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Update: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblMahasiswa.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus!");
            return;
        }
        try {
            String sql = "DELETE FROM mahasiswa WHERE id= ?";
            Connection conn = KoneksiDB.getConnection();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, selectedId);
            pst.executeUpdate();

            tampilData();
            clear();

            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, " Tahun Masuk harus berupa angka!");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void clear() {
        selectedId = -1;
        txtnim.setText("");
        txtnama.setText("");
        txttahun.setText("");
        // Tambahkan reset untuk kolom baru
        txtsks.setText("");
        cbJenis.setSelectedIndex(0); // Set kembali ke pilihan pertama ('Reguler')
        tblMahasiswa.clearSelection();
    }

    ;  
    
    private void tblMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMahasiswaMouseClicked
        // TODO add your handling code here:
        int row = tblMahasiswa.getSelectedRow();
        selectedId = Integer.parseInt(tblMahasiswa.getValueAt(row, 0).toString());
        txtnim.setText(tblMahasiswa.getValueAt(tblMahasiswa.getSelectedRow(), 1).toString());
        txtnama.setText(tblMahasiswa.getValueAt(tblMahasiswa.getSelectedRow(), 2).toString());
        txttahun.setText(tblMahasiswa.getValueAt(tblMahasiswa.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_tblMahasiswaMouseClicked

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        // TODO add your handling code here:
        importCSV();
    }//GEN-LAST:event_btnCSVActionPerformed

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
        hitungDanTampilkanBiaya();
    }//GEN-LAST:event_cbJenisActionPerformed

    private void txtsksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsksActionPerformed
        // TODO add your handling code here:
        hitungDanTampilkanBiaya();
    }//GEN-LAST:event_txtsksActionPerformed
    private void importCSV() {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_ONLY);

        int result = chooser.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {

            java.io.File file = chooser.getSelectedFile();

            try {
                java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file));
                String line;

                // Lewati baris header
                br.readLine();

                Connection conn = KoneksiDB.getConnection();
                String sql = "INSERT INTO mahasiswa (nim, nama, tahunmasuk) VALUES (?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);

                while ((line = br.readLine()) != null) {
                    String[] data = line.split(",");

                    if (data.length == 3) {
                        ps.setString(1, data[0]);                // nim
                        ps.setString(2, data[1]);                // nama
                        ps.setInt(3, Integer.parseInt(data[2])); // tahun masuk
                        ps.addBatch();
                    }
                }

                ps.executeBatch();
                br.close();

                tampilData();
                JOptionPane.showMessageDialog(this, "Import CSV Berhasil!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal import CSV: " + e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiaya;
    private javax.swing.JLabel lblNIM;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tblMahasiswa;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTextField txtsks;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables
}
